"""Fixtures shared between integration and e2e Drizzle tests."""

from __future__ import annotations

import hashlib
import textwrap
from dataclasses import dataclass

import pytest

from iris_pgwire.config import DDLTranslationConfig
from iris_pgwire.migrations.executor import MigrationExecutor
from iris_pgwire.sql_translator.ddl_translator import DDLTranslator


@dataclass(frozen=True)
class DrizzleMigrationFile:
    """Represents a Drizzle-style migration file encountered in production."""

    filename: str
    statements: tuple[str, ...]
    content: str
    hash: str
    target_table: str | None = None

    @classmethod
    def _normalize(cls, sql: str) -> str:
        return textwrap.dedent(sql).strip()

    @classmethod
    def from_sql(
        cls, filename: str, sql: str, target_table: str | None = None
    ) -> "DrizzleMigrationFile":
        normalized = cls._normalize(sql)
        return cls(
            filename=filename,
            statements=(normalized,),
            content=normalized,
            hash=hashlib.sha256(normalized.encode("utf-8")).hexdigest(),
            target_table=target_table,
        )

    @classmethod
    def from_statements(
        cls, filename: str, statements: tuple[str, ...], target_table: str | None = None
    ) -> "DrizzleMigrationFile":
        normalized = tuple(cls._normalize(stmt) for stmt in statements)
        combined = "\n\n".join(normalized)
        return cls(
            filename=filename,
            statements=normalized,
            content=combined,
            hash=hashlib.sha256(combined.encode("utf-8")).hexdigest(),
            target_table=target_table,
        )


@pytest.fixture
def sample_drizzle_migration() -> str:
    """Return a representative Drizzle-generated migration SQL payload."""
    return """
CREATE TABLE "workflow" (
    "id" text PRIMARY KEY NOT NULL,
    "name" text NOT NULL,
    "user_id" text NOT NULL,
    "level" integer DEFAULT 0,
    "key" text,
    "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    "state" text DEFAULT 'pending'
);

ALTER TABLE "workflow" ADD COLUMN "sort_order" integer DEFAULT 0;

CREATE INDEX "workflow_user_id_idx" ON "workflow" ("user_id");
"""


@pytest.fixture
def ddl_translator() -> DDLTranslator:
    """Return a ready-to-use DDLTranslator with default config."""
    config = DDLTranslationConfig(
        strict_mode=False,
        auto_quote_reserved_words=True,
        validate_precision=True,
        lock_timeout_seconds=30,
        fail_fast=True,
    )
    return DDLTranslator(config)


@pytest.fixture
def migration_executor() -> MigrationExecutor:
    """Return a MigrationExecutor instance for integration tests."""
    return MigrationExecutor()


@pytest.fixture
def drizzle_basic_migration_file() -> DrizzleMigrationFile:
    """Sample migration taken from an early Drizzle release."""
    return DrizzleMigrationFile.from_sql(
        "0001_create_workflow.sql",
        """
        -- Drizzle migration (0001_create_workflow.sql)
        -- Generated by Drizzle CLI at 2026-02-09T00:00:00Z
        CREATE TABLE "workflow" (
            "id" text PRIMARY KEY NOT NULL,
            "name" text NOT NULL,
            "user_id" text NOT NULL,
            "level" integer DEFAULT 0,
            "key" text,
            "created_at" timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
            "state" text DEFAULT 'pending'
        );
        """,
        target_table="workflow",
    )


@pytest.fixture
def drizzle_reserved_words_migration_file() -> DrizzleMigrationFile:
    """Migration that uses reserved keywords as column names."""
    return DrizzleMigrationFile.from_sql(
        "0002_reserved_words.sql",
        """
        -- Drizzle migration (0002_reserved_words.sql)
        -- Drizzle uses auto-quoting to protect keywords.
        CREATE TABLE "reserved_words_demo" (
            "level" text,
            "key" text,
            "trigger" text
        );
        """,
        target_table="reserved_words_demo",
    )


@pytest.fixture
def drizzle_type_mapping_migration_file() -> DrizzleMigrationFile:
    """Migration that exercises text, boolean, jsonb, uuid, and timestamp types."""
    return DrizzleMigrationFile.from_sql(
        "0003_type_mapping.sql",
        """
        -- Drizzle migration (0003_type_mapping.sql)
        -- Verify the full set of JSON/UUID/boolean type mappings.
        CREATE TABLE "type_semantics" (
            "id" uuid PRIMARY KEY NOT NULL,
            "description" text NOT NULL,
            "payload" jsonb NOT NULL,
            "is_active" boolean NOT NULL DEFAULT true,
            "event_time" timestamp with time zone NOT NULL,
            "reference_key" uuid
        );
        """,
        target_table="type_semantics",
    )


@pytest.fixture
def drizzle_multi_migration_files() -> tuple[DrizzleMigrationFile, DrizzleMigrationFile]:
    """Return two sequential Drizzle migration files used in deployment scheduling."""
    first = DrizzleMigrationFile.from_sql(
        "0004_create_orders.sql",
        """
        -- Drizzle migration (0004_create_orders.sql)
        CREATE TABLE "orders" (
            "id" uuid PRIMARY KEY NOT NULL,
            "customer" text NOT NULL
        );
        """,
        target_table="orders",
    )
    second = DrizzleMigrationFile.from_sql(
        "0005_create_order_items.sql",
        """
        -- Drizzle migration (0005_create_order_items.sql)
        CREATE TABLE "order_items" (
            "id" uuid PRIMARY KEY NOT NULL,
            "order_id" uuid NOT NULL,
            "description" text NOT NULL
        );
        """,
        target_table="order_items",
    )
    return first, second


@pytest.fixture
def drizzle_failure_migration_file() -> DrizzleMigrationFile:
    """Migration that contains an intentional syntax error to force rollback."""
    return DrizzleMigrationFile.from_statements(
        "0006_failure_example.sql",
        (
            """
            -- Drizzle migration (0006_failure_example.sql)
            CREATE TABLE "rollback_failure_demo" (
                "id" uuid PRIMARY KEY NOT NULL
            );
            """,
            """
            -- The next statement is intentionally malformed.
            CREATE TAABLE "broken_statement" ("id" text);
            """,
            """
            -- This never runs, but Drizzle would emit a third table.
            CREATE TABLE "should_not_exist" (
                "id" text PRIMARY KEY NOT NULL
            );
            """,
        ),
        target_table="rollback_failure_demo",
    )
